spring:
  application:
    name: "kkas"
  datasource:
    url: jdbc:postgresql://localhost:5432/kkasdb
    username: postgres
    password: test
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
